const itemsbs =[
    {
        id: 1,
        name: "The Northern Star",
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        material: "Wood",
        woodType: "oak",
        style: "Transitional",
        customisable: true,
        description: "Wooden engraved wedding hearts, wedding save the date, laser engraving initial pins, unique wedding boutonniere, wedding gift for guest",
        trending: "",
        theme: "",
        image: [
          "/Images/img2.webp",
          '/Images/Bestseller2.jpg',
          '/Images/Bestseller2.jpg',
          '/Images/Bestseller2.jpg',
          '/Images/Bestseller2.jpg',
        ],
        backgroundImage: "/Images/background.jpg",
    },
    {
        id: 2,
        image: "/Images/Bestseller2.jpg",
        isOnSale: true,
        name: "The Northern Star",
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
    },
    {
        id : 3,
        image: "/Images/Bestseller3.jpg",
        isOnSale: true,
        name: "The Northern Star",
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
    },
    {
        id : 4,
        image: "/Images/Bestseller4.jpg",
        isOnSale: true,
        name: "The Northern Star",
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
    },
];

export default itemsbs;