const itemsbs =[
  {
    id: 2,
    name: 'Wooden Heart Wedding Batches-pack of 10',
    rating: 4,
    reviews: 20,
    originalPrice: 1499.0,
    discountedPrice: 999.0,
    image: [
      "/Images/Wood/wooden_heart_wedding_batches/1.webp",
      "/Images/Wood/wooden_heart_wedding_batches/2.webp",
      "/Images/Wood/wooden_heart_wedding_batches/3.webp",
      "/Images/Wood/wooden_heart_wedding_batches/4.webp",
      "/Images/Wood/wooden_heart_wedding_batches/5.webp",
    ],
    material: "Wood",
    style: "Bohemian",
    trending: ["Dopamine", "Coquette" , "Soft Girl Aesthetic"],
    customisable: true,
    giftingguide: "HER",
    type: ["Wooden Art"],
    tags: ["wood", "wedding", "heart" , "batches" , "pins", "handmade"],
    gift:false,
    wallart:false,
    luxury:false,
    theme: "Transitional",
    text1: true,
    photo: false,
    instruction:"1. Write personalization for the product (e.g. Akshay & Aditi, 19.02.2023).",
    size: "4x4 centimeters",
    description: "Personalize your reception, evening event, wedding, or surprise someone with a truly unique gift—our wooden badges are precision-cut and laser-engraved to add a meaningful touch.We offer a wide variety of customizable designs, and we’re always happy to accommodate special requests. Whether you'd like to enlarge the badge or its text for better legibility or reduce it for a more subtle look, we can tailor it to your needs.",
  },
  {
    id: 1,
    name: 'Anime Backlighting Frame',
    rating: 4.5,
    reviews: 38,
    originalPrice: 999.0,
    discountedPrice: 699.0,
    image: [
      "/Images/Anime_Backlighting_Frame/1.avif",
      "/Images/Anime_Backlighting_Frame/2.avif",
      "/Images/Anime_Backlighting_Frame/3.avif",
      "/Images/Anime_Backlighting_Frame/4.avif",
      "/Images/Anime_Backlighting_Frame/5.avif",
    ],
    material: ["Wood"],
    style: "Modern",
    trending: "Dopamine",
    theme: "Safari" ,
    customisable: true,
    giftingguide: ["Freinds", "Family", "HIM"],
    type: ["Table Decors", "Gift"],
    gift: true,
    tags: ["painting", "furniture", "table", "handmade" ,"minimalist"],
    photo: true,
    size: "20Lx15W centimeters",
    luxury: true,
    description: "Discover the mesmerizing charm of light painting – where whimsical stick figures meet enchanting illumination.Brighten up your space with our artistic lamp paintings, thoughtfully crafted to bring both inspiration and elegance to your surroundings.Each piece features a meticulously hand-polished solid wood frame paired with a high-quality, wear-resistant acrylic front—designed for lasting beauty and durability.Perfectly sized at 6 inches by 8 inches, these light paintings make an ideal addition to desks, shelves, or any cozy corner of your home.",
  },
      {
        id: 12,
        name: 'Personalised Spotify Frame',
        rating: 4.5,
        reviews: 38,
        originalPrice: 54443.0,
        discountedPrice: 10000.0,
        image :[
          "/Images/Spotify_Frames/4.webp",
          "/Images/Spotify_Frames/2.webp",
          "/Images/Spotify_Frames/3.webp",
          "/Images/Spotify_Frames/1.webp",
          "/Images/Spotify_Frames/5.webp",
        ],
        material: "Acrylic",
        customisable: true,
        style: ["Modern"],
        trending: ["Dopamine" , "Soft Girl Aesthetic" , "Coquette"],
        giftingguide:["Friends" , "HER" , "HIM" , "Family"],
        type: ["Table Decors"],
        gift: true,
        photo: true, 
        text1: true,
        instruction: [
          "1. Add the song name you want",
          "2. Name of Artist",
          "3. Any txt you want to add (e.g. name , message)",
          "4. Add photo you want to display",
          "5. For queries call +91 7509202484"
        ],
        theme:["Wellness" , "Modern Minimilast"],
        luxury: true,
        description:"Celebrate the special milestone - a beautifully crafted Personalised Photo Print on a high-quality Acrylic Plaque with a sleek stand.",
        size:"10.5Wx14.8L centimeters",
      },
      {
        id: 4,
        name: 'Mini Holograms',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1999.0,
        image :[
          "/Images/Bubble_Gram/4.webp",
          "/Images/Bubble_Gram/2.webp",
          "/Images/Bubble_Gram/3.webp",
          "/Images/Bubble_Gram/1.webp",
          "/Images/Bubble_Gram/5.webp",
        ],
        material: "Glass",
        style: ["Modern", "Bohemian"],
        trending: ["Coquette" , "Soft Girl Aesthetic" , "Dopamine"],
        customisable: true,
        luxury: true,
        giftingguide: ["Friends", "Family" , "HIM" , "HER"],
        type: ["Table Decors"],
        photo: true,
        theme: "Modern Minimilast",
        description: "Turn your cherished memories into a timeless work of art with our Personalized 3D Engraved Crystal Photo with Light Base.This high-quality crystal cube features your favorite photo laser-engraved in stunning 3D detail, creating a lifelike portrait viewable from every angle. The included light base enhances the engraving, casting a soft glow that adds elegance to any space.Perfect for home decor, memorials, anniversaries, or special occasions, this personalized crystal makes a meaningful and lasting gift.Customize it with your chosen photo to create a one-of-a-kind keepsake that celebrates life’s most treasured moments.",
        size: "10Lx7Hx4W centimeters",
      },
];

export default itemsbs;