const itemsbs =[
    {
        id: 2,
        name: "Perosnalised Wooden Heart Badges",
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        material: "Wood",
        woodType: "oak",
        style: "Transitional",
        customisable: true,
        description: "Wooden engraved wedding hearts, wedding save the date, laser engraving initial pins, unique wedding boutonniere, wedding gift for guest",
        trending: "",
        theme: "",
        image: [
          "/Images/img2.webp",
          '/Images/Bestseller2.jpg',
          '/Images/Bestseller2.jpg',
          '/Images/Bestseller2.jpg',
          '/Images/Bestseller2.jpg',
        ],
        backgroundImage: "/Images/background.jpg",
    },
    {
        id: 1,
        name: 'Anime Backlighting Frame',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image: [
          "/Images/Anime Backlighting Frame/1.avif",
          "/Images/Anime Backlighting Frame/2.avif",
          "/Images/Anime Backlighting Frame/3.avif",
          "/Images/Anime Backlighting Frame/4.avif",
          "/Images/Anime Backlighting Frame/5.avif",
        ],
        material: "Resins",
        woodType: "N/A",
        style: "Modern",
        trending: "Soft Girl Aesthetic",
        customisable: true,
        giftingguide: "Family",
      },
      {
        id: 12,
        name: 'Personalised Spotify Frame',
        rating: 4.5,
        reviews: 38,
        originalPrice: 54443.0,
        discountedPrice: 10000.0,
        image :[
          "/Images/Spotify Frames/1.webp",
          "/Images/Spotify Frames/2.webp",
          "/Images/Spotify Frames/3.webp",
          "/Images/Spotify Frames/4.webp",
          "/Images/Spotify Frames/5.webp",
        ],
        customisable: true,
      },
      {
        id: 4,
        name: 'Mini Holograms',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image :[
          "/Images/Bubble Gram/4.webp",
          "/Images/Bubble Gram/2.webp",
          "/Images/Bubble Gram/3.webp",
          "/Images/Bubble Gram/1.webp",
          "/Images/Bubble Gram/5.webp",
        ],
        material: "Glass",
        woodType: "N/A",
        style: "Vintage",
        trending: "Coquette",
        customisable: true,
        giftingguide: "Friends",
      },
];

export default itemsbs;