export const filters = [
    { label: 'Type', options: ['Wall Art', 'Wooden Art', 'Wearables', 'Table Decors', 'Lamps' ] },
    { label: 'Price', options: ['Under ₹1,000', '₹1,000 - ₹3,000', 'Above ₹3,000'] },
  ];
  
  export const products = [
    {
      id: 1,
      name: 'Anime Backlighting Frame',
      rating: 4.5,
      reviews: 38,
      originalPrice: 999.0,
      discountedPrice: 699.0,
      image: [
        "/Images/Anime_Backlighting_Frame/1.avif",
        "/Images/Anime_Backlighting_Frame/2.avif",
        "/Images/Anime_Backlighting_Frame/3.avif",
        "/Images/Anime_Backlighting_Frame/4.avif",
        "/Images/Anime_Backlighting_Frame/5.avif",
      ],
      material: ["Wood"],
      style: "Modern",
      trending: "Dopamine",
      theme: "Safari" ,
      customisable: true,
      giftingguide: ["Freinds", "Family", "HIM"],
      type: ["Table Decors", "Gift"],
      gift: true,
      tags: ["painting", "furniture", "table", "handmade" ,"minimalist"],
      photo: true,
      size: "20Lx15W centimeters",
      luxury: true,
      description: "Discover the mesmerizing charm of light painting – where whimsical stick figures meet enchanting illumination.Brighten up your space with our artistic lamp paintings, thoughtfully crafted to bring both inspiration and elegance to your surroundings.Each piece features a meticulously hand-polished solid wood frame paired with a high-quality, wear-resistant acrylic front—designed for lasting beauty and durability.Perfectly sized at 6 inches by 8 inches, these light paintings make an ideal addition to desks, shelves, or any cozy corner of your home.",
    },

    
    {
      id: 2,
      name: 'Wooden Heart Wedding Batches pack of 10',
      rating: 4,
      reviews: 20,
      originalPrice: 1499.0,
      discountedPrice: 999.0,
      image: [
        "/Images/Wood/wooden_heart_wedding_batches/1.webp",
        "/Images/Wood/wooden_heart_wedding_batches/2.webp",
        "/Images/Wood/wooden_heart_wedding_batches/3.webp",
        "/Images/Wood/wooden_heart_wedding_batches/4.webp",
        "/Images/Wood/wooden_heart_wedding_batches/5.webp",
      ],
      material: "Wood",
      style: "Bohemian",
      trending: ["Dopamine", "Coquette" , "Soft Girl Aesthetic"],
      customisable: true,
      giftingguide: "HER",
      type: ["Wooden Art"],
      tags: ["wood", "wedding", "heart" , "batches" , "pins", "handmade"],
      gift:false,
      wallart:false,
      luxury:false,
      theme: "Transitional",
      text1: true,
      photo: false,
      instruction:"1. Write personalization for the product (e.g. Akshay & Aditi, 19.02.2023).",
      size: "4x4 centimeters",
      description: "Personalize your reception, evening event, wedding, or surprise someone with a truly unique gift—our wooden badges are precision-cut and laser-engraved to add a meaningful touch.We offer a wide variety of customizable designs, and we’re always happy to accommodate special requests. Whether you'd like to enlarge the badge or its text for better legibility or reduce it for a more subtle look, we can tailor it to your needs.",
    },
    {
      id: 3,
      name: "Personalized Laser Wooden Engrave Photo",
      rating: 5,
      reviews: 40,
      originalPrice: 1590.0,
      discountedPrice: 499.0,
      material: "Wood",
      style: "Transitional",
      customisable: true,
      trending: ["Dopamine" , "Coquette" , "Soft Girl Aesthetic"],
      theme: "Modern Minimilast",
      image: [
        "/Images/Wood/personalised_wooden_laser_engraved_photo/1.webp",
        "/Images/Wood/personalised_wooden_laser_engraved_photo/2.webp",
        "/Images/Wood/personalised_wooden_laser_engraved_photo/3.webp",
        "/Images/Wood/personalised_wooden_laser_engraved_photo/4.webp",
        "/Images/Wood/personalised_wooden_laser_engraved_photo/5.webp",
      ],
      giftingguide: "HIM",
      type: ["Wooden Art", "Table Decors", "Wall Art"],
      photo: true,
      text1: true,
      wallart: true,
      luxury: true,
      instruction: [
        "1. Add text you want to engrave on the front/back (e.g. Name, date, occasion, message)",
        "2. For any other modification WhatsApp on +91 7509202484"
      ],
      size: "12.5Lx10W centimeters",
      description: "A truly one-of-a-kind keepsake, perfect for celebrating special moments like anniversaries, births, or honoring the memory of a loved one—including pets. This wooden photo gift makes a heartfelt gesture for anyone—whether it's a partner, parent, best friend, or grandparent.Beautifully laser-engraved on 1/4” maple plywood, it’s a lasting alternative to traditional photographs—resistant to fading and growing more meaningful with timeYou can also personalize it further with custom text or graphics, making it an even more treasured heirloom for years to come.",
    },
    {
      id: 4,
      name: 'Mini Holograms',
      rating: 4.5,
      reviews: 38,
      originalPrice: 3499.0,
      discountedPrice: 1999.0,
      image :[
        "/Images/Bubble_Gram/4.webp",
        "/Images/Bubble_Gram/2.webp",
        "/Images/Bubble_Gram/3.webp",
        "/Images/Bubble_Gram/1.webp",
        "/Images/Bubble_Gram/5.webp",
      ],
      material: "Glass",
      style: ["Modern", "Bohemian"],
      trending: ["Coquette" , "Soft Girl Aesthetic" , "Dopamine"],
      customisable: true,
      luxury: true,
      giftingguide: ["Friends", "Family" , "HIM" , "HER"],
      type: ["Table Decors"],
      photo: true,
      theme: "Modern Minimilast",
      description: "Turn your cherished memories into a timeless work of art with our Personalized 3D Engraved Crystal Photo with Light Base.This high-quality crystal cube features your favorite photo laser-engraved in stunning 3D detail, creating a lifelike portrait viewable from every angle. The included light base enhances the engraving, casting a soft glow that adds elegance to any space.Perfect for home decor, memorials, anniversaries, or special occasions, this personalized crystal makes a meaningful and lasting gift.Customize it with your chosen photo to create a one-of-a-kind keepsake that celebrates life’s most treasured moments.",
      size: "10Lx7Hx4W centimeters",
    },
    {
        id: 5,
        name: 'Customised Ash Tray',
        rating: 3.5,
        reviews: 19,
        originalPrice: 2999.0,
        discountedPrice: 1999.0,
        image:[
          "/Images/Wood/Customised_Ash_Tray/1.webp",
          "/Images/Wood/Customised_Ash_Tray/2.avif",
          "/Images/Wood/Customised_Ash_Tray/3.avif",
          "/Images/Wood/Customised_Ash_Tray/4.avif",
          "/Images/Wood/Customised_Ash_Tray/5.jpg", 
        ],
        style:"Vintage",
        trending: "Dopamine",
        customisable: true,
        giftingguide: "Office",
        type: ["Table Decors"],
        gift: true,
        photo: true,
        text1: true,
        instruction: [
          "1. Add name, logo, or text you want to engrave ",
          "2. For any other modification WhatsApp on +91 7509202484"
        ],
        theme: "Office Essentials",
        material: "Wood",
        description: "Wedding Gift Wooden Cigar Holder, Custom Monogram Cigar Pairing Tray, Whiskey Gift Set, Anniversary Gift, Personalized Gift for Couples",
        size: "",
        luxury: true,
      },
      {
        id: 6,
        name: 'Customisable 3d Family Figurines',
        rating: 3.5,
        reviews: 20,
        originalPrice: 3999.0,
        discountedPrice: 2999.0,
        image:[
          "/Images/3d_Miniatures/customisable/5.jpeg",
          "/Images/3d_Miniatures/customisable/2.jpg",
          "/Images/3d_Miniatures/customisable/3.jpeg",
          "/Images/3d_Miniatures/customisable/4.jpeg",
          "/Images/3d_Miniatures/customisable/1.webp", 
        ],
        material: "Resin",
        trending: ["Dopamine", "Soft Girl Aesthetic"],
        customisable: true,
        giftingguide: ["Family" , "Friends" , "HIM" , "HER"],
        type: ["Table Decors"],
        gift: true,
        photo: true,
        theme: "Modern Minimilast",
        description: "Our figures are meticulously produced using 12K SLA 3D printers, providing high clarity and resolution with a layer height of 0.4.",
        size: "6 inches",
      },
      {
        id: 7,
        name: 'Fictional Characters Miniatures',
        rating: 4,
        reviews: 40,
        originalPrice: 5499.0,
        discountedPrice: 3499.0,
        image:[
          "/Images/3d_Miniatures/anime_custom/1.avif",
          "/Images/3d_Miniatures/anime_custom/2.avif",
          "/Images/3d_Miniatures/anime_custom/3.avif",
          "/Images/3d_Miniatures/anime_custom/4.avif",
          "/Images/3d_Miniatures/anime_custom/5.avif", 
        ],
        material: "Resin",
        style: ["Modern" , "Bohemian"],
        trending: ["Dopamine"],
        customisable: true,
        giftingguide:["Friends" , "HIM"],
        type: ["Table Decors"],
        gift: true,
        photo: true,
        theme:"Modern Minimilast",
        description:"Our figures are meticulously produced using 12K SLA 3D printers, providing high clarity and resolution with a layer height of 0.4.",
        size:"6 inches",
      },
      {
        id: 8,
        name: '2D Wall Hanging Acrylic Cutouts ',
        rating: 3.5,
        reviews: 42,
        originalPrice: 2499.0,
        discountedPrice: 1499.0,
        image:[
          "/Images/2D_Cutouts/1.jpg",
          "/Images/2D_Cutouts/2.jpg",
          "/Images/2D_Cutouts/3.jpg",
          "/Images/2D_Cutouts/4.jpg",
          "/Images/2D_Cutouts/5.jpg", 
        ],
        material: "acrylic",
        style: ["Modern"],
        trending: ["Dopamine"],
        customisable: true,
        giftingguide:["Friends" , "Family"],
        type: ["Wall Art"],
        gift: true,
        photo: true,
        theme:"Modern Minimilast",
        description:"",
        size:"20Wx30L centimeters",
        wallart: true,
      },
      {
        id: 9,
        name: 'Personalised Jewellary',
        rating: 4.5,
        reviews: 38,
        discountedPrice: "Contact on +91 7509202484 for price details",
        originalPrice: "Max price will go to 1599",
        image :[
          "/Images/Wearables/Jewellary/1.webp",
          "/Images/Wearables/Jewellary/2.webp",
          "/Images/Wearables/Jewellary/3.webp",
          "/Images/Wearables/Jewellary/4.webp",
          "/Images/Wearables/Jewellary/5.webp",
        ],
        material: "Gold , Silver , Rose Gold",
        customisable: true,
        personalisedjewellary: true,
        style: ["Modern"],
        trending: ["Dopamine" , "Soft Girl Aesthetic" , "Coquette"],
        giftingguide:["Friends" , "HER"],
        type: ["Jewellary", "Wearables"],
        gift: true,
        text1: true,
        instruction: [
          "1. Contact on +91 7509202484",
        ],
        theme:["Wellness" , "Modern Minimilast"],
        luxury: true,
        description:"Custom Name Necklace, 18K Gold Plated Name Necklace, Personalized Name Necklace, Birthday Gift for Her, Mother's Day Gift, Gift for Mom",
        size:"18 inches",
      },
      {
        id: 10,
        name: 'Customisable Embriored Hoodies and T-Shirts',
        rating: 4,
        reviews: 30,
        originalPrice: 2499.0,
        discountedPrice: 1999.0,
        image :[
          "/Images/Wearables/Embriodary/1.webp",
          "/Images/Wearables/Embriodary/2.webp",
          "/Images/Wearables/Embriodary/3.webp",
          "/Images/Wearables/Embriodary/4.webp",
          "/Images/Wearables/Embriodary/5.webp",
        ],
        material: "cotton fleece",
        customisable: true,
        style: ["Modern" , "Transitional"],
        trending: ["Dopamine" , "Soft Girl Aesthetic" , "Coquette"],
        giftingguide:["Friends" , "HER" , "Family" , "HIM"],
        type: ["Wearables"],
        gift: true,
        text1: true,
        instruction: [
          "1. Add the name you want (maximum 7 letters)",
          "2. For queries call +91 7509202484"
        ],
        theme:["Wellness" , "Modern Minimilast"],
        description:"Sweatshirts and Hoodies with long-lasting embroidery, Crafted with the utmost care and creativity, this sweatshirt is more than just clothing; it's a wearable masterpiece waiting to be personalized by you.",
        size:"",
      },
      {
        id: 11,
        name: 'Castle Modelled Lamp',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 2499.0,
        image :[
          "/Images/Lamp/Castle_Modeled_Lamp/1.avif",
          "/Images/Lamp/Castle_Modeled_Lamp/2.avif",
          "/Images/Lamp/Castle_Modeled_Lamp/3.avif",
          "/Images/Lamp/Castle_Modeled_Lamp/4.avif",
        ],
        material: "Resin",
        style: ["Modern"],
        trending: ["Dopamine" , "Soft Girl Aesthetic" , "Coquette"],
        giftingguide:["Friends" , "HER" , "HIM"],
        type: ["Lamp"],
        gift: true,
        theme:["Wellness" , "Modern Minimilast"],
        luxury: true,
        description:"Castle night light is the perfect addition to your child's bedroom or to rekindle your childhood memories. We know you will love this light! These also work GREAT for Cake Toppers!",
        size:"8Lx10Wx8H inches",
      },
      {
        id: 12,
        name: 'Personalised Spotify Frame',
        rating: 4.5,
        reviews: 38,
        originalPrice: 54443.0,
        discountedPrice: 10000.0,
        image :[
          "/Images/Spotify_Frames/4.webp",
          "/Images/Spotify_Frames/2.webp",
          "/Images/Spotify_Frames/3.webp",
          "/Images/Spotify_Frames/1.webp",
          "/Images/Spotify_Frames/5.webp",
        ],
        customisable: true,
        material: "Acrylic",
        style: ["Modern"],
        trending: ["Dopamine" , "Soft Girl Aesthetic" , "Coquette"],
        giftingguide:["Friends" , "HER" , "HIM" , "Family"],
        type: ["Table Decors"],
        gift: true,
        photo: true, 
        text1: true,
        instruction: [
          "1. Add the song name you want",
          "2. Name of Artist",
          "3. Any txt you want to add (e.g. name , message)",
          "4. Add photo you want to display",
          "5. For queries call +91 7509202484"
        ],
        theme:["Wellness" , "Modern Minimilast"],
        luxury: true,
        description:"Celebrate the special milestone - a beautifully crafted Personalised Photo Print on a high-quality Acrylic Plaque with a sleek stand.",
        size:"10.5Wx14.8L centimeters",
      },
      {
        id: 13,
        name: 'Customisable Spotify Key Chain',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image :[
          "/Images/Key_Chains/Spotify/1.webp",
          "/Images/Key_Chains/Spotify/2.webp",
          "/Images/Key_Chains/Spotify/3.webp",
          "/Images/Key_Chains/Spotify/4.webp",
          "/Images/Key_Chains/Spotify/5.webp",
        ],
        material: "Metal",
        customisable: true,
        style: ["Modern"],
        trending: ["Dopamine" , "Soft Girl Aesthetic" , "Coquette"],
        giftingguide:["Friends" , "HER" , "Family" , "HIM"],
        type: ["Key Chain"],
        gift: true,
        text1: true,
        instruction: [
          "1. Add the name of song and artist ",
          "2. Add message you want and font style (e.g. 'Love You , arial')",
          "3. For queries call +91 7509202484"
        ],
        theme:["Wellness" , "Modern Minimilast"],
        description:"Our Spotify Code Keychain is a brilliant fusion of fashion and functionality that lets you carry your favourite songs, playlists, or artists wherever you go",
        size:"5 centimeters long",
      },
      {
        id: 14,
        name: 'Personalised Fingerprint Key Chain',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image :[
          "/Images/Key_Chains/Fingerprint/1.webp",
          "/Images/Key_Chains/Fingerprint/2.webp",
          "/Images/Key_Chains/Fingerprint/3.webp",
          "/Images/Key_Chains/Fingerprint/4.webp",
          "/Images/Key_Chains/Fingerprint/5.webp",
        ],
        material: "Metal",
        customisable: true,
        style: ["Modern"],
        trending: ["Dopamine" , "Soft Girl Aesthetic" , "Coquette"],
        giftingguide:["Friends" , "HER" , "HIM" , "Family"],
        type: ["Key Chain"],
        gift: true,
        text1: true,
        photo:true,
        instruction: [
          "1. Add the text you want (frontside)",
          "2. Add the text you want (backside)",
          "3. Add photo of your fingerprint",
          "4. For queries call +91 7509202484"
        ],
        theme:["Wellness" , "Modern Minimilast"],
        luxury: true,
        description:"Your ACTUAL finger print engraved on these beautiful military tag key chains. These meaningful key chains make the perfect gift for your best friend, family or yourself! Our finger print key chains are engraved with a high precision laser engraver. Prepare your finger print is easy! Please read our instruction below and on the photos and send us your print direct from your phone!",size:"",
      },
      {
        id: 15,
        name: 'Wooden Laser Engraved Text',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image :[
          "/Images/Wood/wooden_laser_engraved_text/1.webp",
          "/Images/Wood/wooden_laser_engraved_text/2.webp",
          "/Images/Wood/wooden_laser_engraved_text/3.webp",
          "/Images/Wood/wooden_laser_engraved_text/4.webp",
          "/Images/Wood/wooden_laser_engraved_text/5.webp",
        ],
        material: "Wood",
        customisable: true,
        style: ["Traditional"],
        giftingguide:["Family"],
        type: ["Table Decor"],
        text1: true,
        instruction: [
          "1. Add the text you want",
          "2. For queries call +91 7509202484"
        ],
        theme:["Earthy"],
        luxury: true,
        description:"Your Handwritten Letter Gift Personalized Message Custom Engraved Wood Plank Wedding Vows Engraved Letter on Wood Custom Poem on Wood Plaque Gift on Wooden Gift for your loved one",
        size:"8Lx10W inches",
      },
      {
        id: 16,
        name: 'Zebra Wall Art',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image :[
          "/Images/Wall_Art/3.webp",
          "/Images/Wall_Art/2.webp",
          "/Images/Wall_Art/1.webp",
          "/Images/Wall_Art/4.webp",
          "/Images/Wall_Art/5.webp",
        ],
        material: "Acrylic",
        style: ["Modern"],
        trending: ["Dopamine" , "Soft Girl Aesthetic" , "Coquette"],
        giftingguide:["Friends" , "HER" , "HIM" , "Family"],
        type: ["Wall Art"],
        theme:["Wellness" , "Modern Minimilast"],
        wallart: true,
        description:"Get up close and personal with the striking beauty of this zebra poster, where every stripe tells a story of nature's artistry. Bring the wild into your space with this captivating snapshot of the animal kingdom. A perfect gift for animal enthusiasts, young and old!",
        size:"8Wx12L inches",
      },
      {
        id: 17,
        name: 'Abstract Wall Art',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image :[
          "/Images/Wall_Art/Circle/1.webp",
          "/Images/Wall_Art/Circle/2.webp",
          "/Images/Wall_Art/Circle/3.webp",
          "/Images/Wall_Art/Circle/4.webp",
          "/Images/Wall_Art/Circle/5.webp",
        ],
        material: "Acrylic",
        style: ["Modern"],
        trending: ["Dopamine" , "Soft Girl Aesthetic" , "Coquette"],
        giftingguide:["Friends" , "HER" , "HIM" , "Family"],
        type: ["Wall Art"],
        theme:["Wellness" , "Modern Minimilast"],
        wallart: true,
        description:"Abstract Painting",
        luxury: true,
        size:"",
      },
      {
        id: 18,
        name: 'Parametric Cubic Wall Art',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image :[
          "/Images/Wall_Art/Parametric/Cube/1.webp",
          "/Images/Wall_Art/Parametric/Cube/2.webp",
          "/Images/Wall_Art/Parametric/Cube/3.webp",
          "/Images/Wall_Art/Parametric/Cube/4.webp",
          "/Images/Wall_Art/Parametric/Cube/5.webp",
        ],
        material: "Acrylic",
        style: ["Modern"],
        trending: ["Dopamine" , "Soft Girl Aesthetic" , "Coquette"],
        giftingguide:["Friends" , "HER" , "HIM" , "Family"],
        type: ["Wall Art"],
        theme:["Wellness" , "Modern Minimilast"],
        wallart: true,
        description:"Make a bold statement with this striking geometric wall hanging, a fusion of modern design and interactive art.The design plays with light and shadow, shifting throughout the day to create a dynamic, ever-changing effect on your wall.",
        size:"",
        luxury: true,
      },
  ];
  