export const filters = [
    { label: 'Type', options: ['Wall Art', 'Wooden Art', 'Wearables', 'Table Decors', 'Lamps' ] },
    { label: 'Price', options: ['Under ₹1,000', '₹1,000 - ₹3,000', 'Above ₹3,000'] },
  ];
  
  export const products = [
    {
      id: 1,
      name: 'Anime Backlighting Frame',
      rating: 4.5,
      reviews: 38,
      originalPrice: 3499.0,
      discountedPrice: 1699.0,
      image: [
        "/Images/Anime_Backlighting_Frame/1.avif",
        "/Images/Anime_Backlighting_Frame/2.avif",
        "/Images/Anime_Backlighting_Frame/3.avif",
        "/Images/Anime_Backlighting_Frame/4.avif",
        "/Images/Anime_Backlighting_Frame/5.avif",
      ],
      material: "Resins",
      woodType: "N/A",
      style: "Modern",
      trending: "Soft Girl Aesthetic",
      customisable: true,
      giftingguide: "Family",
      type: "Table Decors",
      backgroundImage: "/Images/tbg.jpg",
      isDraggable: false,
      preview: "PREVIEW",
      frameImageURL: "animeframe1.jpg",
    },

    
    {
      id: 2,
      name: 'Wooden Heart Wedding Batches',
      rating: 4.5,
      reviews: 38,
      originalPrice: 3499.0,
      discountedPrice: 1699.0,
      image: [
        "/Images/Wood/wooden_heart_wedding_batches/1.webp",
        "/Images/Wood/wooden_heart_wedding_batches/2.webp",
        "/Images/Wood/wooden_heart_wedding_batches/3.webp",
        "/Images/Wood/wooden_heart_wedding_batches/4.webp",
        "/Images/Wood/wooden_heart_wedding_batches/5.webp",
      ],
      material: "Wood",
      woodType: "N/A",
      style: "Traditional",
      trending: "Dopamine",
      customisable: true,
      giftingguide: "HER",
      type: "Wooden Art",
    },
    {
      id: 3,
      name: "Personalized Laser Wooden Engrave Photo",
      rating: 4.5,
      reviews: 38,
      originalPrice: 3499.0,
      discountedPrice: 1699.0,
      material: "Wood",
      woodType: "oak",
      style: "Transitional",
      customisable: true,
      description: "Wooden engraved wedding hearts, wedding save the date, laser engraving initial pins, unique wedding boutonniere, wedding gift for guest",
      trending: "",
      theme: "",
      image: [
        "/Images/Wood/personalised_wooden_laser_engraved_photo/1.webp",
        "/Images/Wood/personalised_wooden_laser_engraved_photo/2.webp",
        "/Images/Wood/personalised_wooden_laser_engraved_photo/3.webp",
        "/Images/Wood/personalised_wooden_laser_engraved_photo/4.webp",
        "/Images/Wood/personalised_wooden_laser_engraved_photo/5.webp",
      ],
      backgroundImage: "/Images/background.jpg",
      giftingguide: "HIM",
      type: "Wooden Art , Table Decors , Wall Art"
    },
    {
      id: 4,
      name: 'Mini Holograms',
      rating: 4.5,
      reviews: 38,
      originalPrice: 3499.0,
      discountedPrice: 1699.0,
      image :[
        "/Images/Bubble_Gram/4.webp",
        "/Images/Bubble_Gram/2.webp",
        "/Images/Bubble_Gram/3.webp",
        "/Images/Bubble_Gram/1.webp",
        "/Images/Bubble_Gram/5.webp",
      ],
      material: "Glass",
      woodType: "N/A",
      style: "Vintage",
      trending: "Coquette",
      customisable: true,
      giftingguide: "Friends",
      type: "Table Decors",
      backgroundImage: "/Images/tbg.jpg",
      preview: "PREVIEW",
      frameImageURL: "bubblegramframe1.png",
    },
    {
        id: 5,
        name: 'Customised Ash Tray',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image:[
          "/Images/Wood/Customised_Ash_Tray/1.webp",
          "/Images/Wood/Customised_Ash_Tray/2.avif",
          "/Images/Wood/Customised_Ash_Tray/3.avif",
          "/Images/Wood/Customised_Ash_Tray/4.avif",
          "/Images/Wood/Customised_Ash_Tray/5.jpg", 
        ],
        customisable: true,
        giftingguide: "Office",
        material: "Wood",
      },
      {
        id: 6,
        name: 'Customisable 3d Family Figurines',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image:[
          "/Images/3d_Miniatures/customisable/5.jpeg",
          "/Images/3d_Miniatures/customisable/2.jpg",
          "/Images/3d_Miniatures/customisable/3.jpeg",
          "/Images/3d_Miniatures/customisable/4.jpeg",
          "/Images/3d_Miniatures/customisable/1.webp", 
        ],
        customisable: true,
      },
      {
        id: 7,
        name: 'Fictional Characters Miniatures',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image:[
          "/Images/3d_Miniatures/anime_custom/1.avif",
          "/Images/3d_Miniatures/anime_custom/2.avif",
          "/Images/3d_Miniatures/anime_custom/3.avif",
          "/Images/3d_Miniatures/anime_custom/4.avif",
          "/Images/3d_Miniatures/anime_custom/5.avif", 
        ],
        customisable: true,
      },
      {
        id: 8,
        name: '2D Wall Hanging Acrylic Cutouts ',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image:[
          "/Images/2D_Cutouts/1.jpg",
          "/Images/2D_Cutouts/2.jpg",
          "/Images/2D_Cutouts/3.jpg",
          "/Images/2D_Cutouts/4.jpg",
          "/Images/2D_Cutouts/5.jpg", 
        ],
        material: "acrylic",
        customisable: true,
      },
      {
        id: 9,
        name: 'Personalised Jewellary',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image :[
          "/Images/Wearables/Jewellary/1.webp",
          "/Images/Wearables/Jewellary/2.webp",
          "/Images/Wearables/Jewellary/3.webp",
          "/Images/Wearables/Jewellary/4.webp",
          "/Images/Wearables/Jewellary/5.webp",
        ],
        customisable: true,
      },
      {
        id: 10,
        name: 'Customisable Embriored Hoodies and T-Shirts',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image :[
          "/Images/Wearables/Embriodary/1.webp",
          "/Images/Wearables/Embriodary/2.webp",
          "/Images/Wearables/Embriodary/3.webp",
          "/Images/Wearables/Embriodary/4.webp",
          "/Images/Wearables/Embriodary/5.webp",
        ],
        customisable: true,
      },
      {
        id: 11,
        name: 'Castle Modelled Lamp',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image :[
          "/Images/Lamp/Castle_Modeled_Lamp/1.avif",
          "/Images/Lamp/Castle_Modeled_Lamp/2.avif",
          "/Images/Lamp/Castle_Modeled_Lamp/3.avif",
          "/Images/Lamp/Castle_Modeled_Lamp/4.avif",
        ],
        customisable: true,
      },
      {
        id: 12,
        name: 'Personalised Spotify Frame',
        rating: 4.5,
        reviews: 38,
        originalPrice: 54443.0,
        discountedPrice: 10000.0,
        image :[
          "/Images/Spotify_Frames/1.webp",
          "/Images/Spotify_Frames/2.webp",
          "/Images/Spotify_Frames/3.webp",
          "/Images/Spotify_Frames/4.webp",
          "/Images/Spotify_Frames/5.webp",
        ],
        customisable: true,
        type: "Table Decors",
        backgroundImage: "/Images/tbg.jpg",
        isDraggable: false,
        preview: "PREVIEW",
        frameImageURL: "spotifyframe1.jpg",
      },
      {
        id: 13,
        name: 'Customisable Spotify Key Chain',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image :[
          "/Images/Key_Chains/Spotify/1.webp",
          "/Images/Key_Chains/Spotify/2.webp",
          "/Images/Key_Chains/Spotify/3.webp",
          "/Images/Key_Chains/Spotify/4.webp",
          "/Images/Key_Chains/Spotify/5.webp",
        ],
        customisable: true,
      },
      {
        id: 14,
        name: 'Personalised Fingerprint Key Chain',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image :[
          "/Images/Key_Chains/Fingerprint/1.webp",
          "/Images/Key_Chains/Fingerprint/2.webp",
          "/Images/Key_Chains/Fingerprint/3.webp",
          "/Images/Key_Chains/Fingerprint/4.webp",
          "/Images/Key_Chains/Fingerprint/5.webp",
        ],
        customisable: true,
      },
      {
        id: 15,
        name: 'Wooden Laser Engraved Text',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image :[
          "/Images/Wood/wooden_laser_engraved_text/1.webp",
          "/Images/Wood/wooden_laser_engraved_text/2.webp",
          "/Images/Wood/wooden_laser_engraved_text/3.webp",
          "/Images/Wood/wooden_laser_engraved_text/4.webp",
          "/Images/Wood/wooden_laser_engraved_text/5.webp",
        ],
        customisable: true,
      },
      {
        id: 16,
        name: 'Zebra Wall Art',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image :[
          "/Images/Wall_Art/3.webp",
          "/Images/Wall_Art/2.webp",
          "/Images/Wall_Art/1.webp",
          "/Images/Wall_Art/4.webp",
          "/Images/Wall_Art/5.webp",
        ],
      },
      {
        id: 17,
        name: 'Abstract Wall Art',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image :[
          "/Images/Wall_Art/Circle/1.webp",
          "/Images/Wall_Art/Circle/2.webp",
          "/Images/Wall_Art/Circle/3.webp",
          "/Images/Wall_Art/Circle/4.webp",
          "/Images/Wall_Art/Circle/5.webp",
        ],
      },
      {
        id: 18,
        name: 'Parametric Cubic Wall Art',
        rating: 4.5,
        reviews: 38,
        originalPrice: 3499.0,
        discountedPrice: 1699.0,
        image :[
          "/Images/Wall_Art/Parametric/Cube/1.webp",
          "/Images/Wall_Art/Parametric/Cube/2.webp",
          "/Images/Wall_Art/Parametric/Cube/3.webp",
          "/Images/Wall_Art/Parametric/Cube/4.webp",
          "/Images/Wall_Art/Parametric/Cube/5.webp",
        ],
      },
  ];
  